Repository BinaryStudioAcademy/bsa-2018-kudypoditys, pull requests merged in 2018-08, with the labels that each got.

#23 added redux state management
  src/client/components/ranking-bar/container.jsx
  src/client/components/ranking-bar/index.jsx
  src/client/index.js
  src/client/logic/defaultState.js
  src/client/logic/ranking-bar/actionTypes.js
  src/client/logic/ranking-bar/actions.js
  src/client/logic/ranking-bar/reducer.js
  src/client/logic/reducer.js
  stories/RankingBar.stories.js
Labels: enhancement

#29 connected banner container to store
  src/client/components/banner-list/container.jsx
  src/client/components/banner-list/index.jsx
  src/client/logic/banner-list/actionType.js
  src/client/logic/banner-list/actions.js
  src/client/logic/banner-list/reducer.js
  src/client/logic/defaultState.js
  src/client/logic/reducer.js
Labels: enhancement

#24 39 search summary container
  src/client/components/search-summary/container.jsx
  src/client/components/search-summary/index.jsx
  src/client/index.js
  src/client/logic/defaultState.js
  src/client/logic/reducer.js
  src/client/logic/search-summary/actionTypes.js
  src/client/logic/search-summary/actions.js
  src/client/logic/search-summary/reducer.js
Labels: enhancement

#27 41 property description container
  src/client/components/property-description/container.jsx
  src/client/components/property-description/index.jsx
  src/client/index.js
  src/client/logic/defaultState.js
  src/client/logic/property-description/actionTypes.js
  src/client/logic/property-description/actions.js
  src/client/logic/property-description/reducer.js
  src/client/logic/reducer.js
Labels: enhancement

#54 basic view
  src/client/components/property-creation-tabs/container.jsx
  src/client/components/property-creation-tabs/index.jsx
  src/client/components/property-creation-tabs/index.scss
  src/client/index.js
Labels: enhancement

#42 44-home page
  src/client/components/app/index.js
  src/client/components/banner-list/container.jsx
  src/client/components/banner-list/index.jsx
  src/client/components/banner-list/item.jsx
  src/client/components/home-page/container.jsx
  src/client/components/home-page/index.jsx
  src/client/components/home-page/index.scss
  src/client/components/search/index.jsx
  src/client/index.js
  src/client/logic/banner-list/reducer.js
  stories/BannerList.stories.js
Labels: enhancement

#64 Added error feedback, fixed validation error.
  package-lock.json
  src/client/components/input-form/renderField.jsx
  src/client/components/registration/container.jsx
  src/client/components/registration/form.js
  src/client/components/registration/index.jsx
  src/client/components/registration/validate.js
  src/client/logic/registration/actionTypes.js
  src/client/logic/registration/actions.js
  src/client/logic/registration/reducer.js
Labels: enhancement

#68 70 checkin checkout component
  config/webpack.config.prod.js
  package.json
  server.js
  src/api/routes/index.js
  src/client/components/app/index.js
  src/client/components/banner-list/item.jsx
  src/client/components/basic-map-widget/index.jsx
  src/client/components/basic-map-widget/map.jsx
  src/client/components/breadcrumbs/index.jsx
  src/client/components/checkin-checkout/DrawInputs.js
  src/client/components/checkin-checkout/config.js
  src/client/components/checkin-checkout/container.jsx
  src/client/components/checkin-checkout/index.jsx
  src/client/components/checkin-checkout/index.scss
  src/client/components/header/container.jsx
  src/client/components/header/index.jsx
  src/client/components/header/index.scss
  src/client/components/home-page/index.jsx
  src/client/components/map-view/index.jsx
  src/client/components/map-view/map.jsx
  src/client/components/property-list-item/index.jsx
  src/client/components/property-page/index.jsx
  src/client/components/quick-filter/container.jsx
  src/client/components/quick-filter/filters.js
  src/client/components/quick-filter/index.jsx
  src/client/components/quick-filter/index.scss
  src/client/components/registration/form.js
  src/client/components/rooms-summary-table/container.js
  src/client/components/rooms-summary-table/index.jsx
  src/client/components/rooms-summary-table/index.scss
  src/client/components/rooms-summary-table/modal.jsx
  src/client/components/search-page/index.jsx
  src/client/components/search-summary/index.jsx
  src/client/components/search/index.jsx
  src/client/components/slider/index.jsx
  src/client/index.js
  src/client/logic/banner-list/reducer.js
  src/client/logic/checkIn-checkOut/actionTypes.js
  src/client/logic/checkIn-checkOut/actions.js
  src/client/logic/checkIn-checkOut/reducer.js
  src/client/logic/defaultState.js
  src/client/logic/header/reducer.js
  src/client/logic/quick-filter/actions.js
  src/client/logic/quick-filter/reducer.js
  src/client/logic/reducer.js
  src/client/logic/rooms-summary-table/actions.js
  stories/BannerList.stories.js
  stories/Header.stories.js
  stories/MapView.stories.js
  stories/QuickFilter.stories.js
  stories/RoomSummaryTable.stories.js
  stories/index.stories.js
  stories/quick-filter.stories.js
  yarn.lock
Labels: enhancement

#71 48 login
  config/settings.js
  package-lock.json
  package.json
  server.js
  src/api/associations.js
  src/api/helpers/date-helpers.js
  src/api/helpers/index.js
  src/api/helpers/unless.js
  src/api/middleware/index.js
  src/api/middleware/jwt.middleware.js
  src/api/models/UserRefreshToken.js
  src/api/orm.js
  src/api/repositories/UserRepository.js
  src/api/repositories/generalRepository.js
  src/api/repositories/userRefreshTokenRepository.js
  src/api/repositories/userRepository.js
  src/api/routes/authRoutes.js
  src/api/routes/index.js
  src/api/routes/userRoutes.js
  src/api/services/generalService.js
  src/api/services/user.js
  src/api/services/userToken.js
  src/api/testModels.js
  src/client/components/header/container.jsx
  src/client/components/header/index.jsx
  src/client/components/home-page/index.jsx
  src/client/components/registration/form.js
  src/client/helpers/api.js
  src/client/helpers/date-helpers.js
  src/client/history.js
  src/client/index.js
  src/client/logic/defaultState.js
  src/client/logic/header/actionTypes.js
  src/client/logic/header/actions.js
  src/client/logic/header/reducer.js
  src/client/logic/header/saga.js
  src/client/logic/login/actionTypes.js
  src/client/logic/login/actions.js
  src/client/logic/login/reducer.js
  src/client/logic/login/saga.js
  src/client/logic/registration/actionTypes.js
  src/client/logic/registration/actions.js
  src/client/logic/rootSaga.js
  src/client/services/authService.js
  src/client/services/userService.js
  yarn.lock
Labels: enhancement

#72 36 registration container
  src/client/components/input-form/renderField.jsx
  src/client/components/registration/form.js
  src/client/components/registration/index.scss
  src/client/components/registration/validate.js
  src/client/regexValidationService.js
Labels: enhancement

#73 added semantic selector w/ redux-form
  src/client/components/dropdown-form/container.jsx
  src/client/components/dropdown-form/index.jsx
  src/client/components/dropdown-form/index.scss
  src/client/components/dropdown-form/semanticSelectorForm.jsx
Labels: enhancement

#75 added remastered property creation tabs
  src/client/components/property-creation-tabs/DrawTab.jsx
  src/client/components/property-creation-tabs/config.js
  src/client/components/property-creation-tabs/index.jsx
Labels: enhancement

#80 added db connection dependency on environment variable
  .env
  package.json
  src/api/orm.js
  yarn.lock
Labels: enhancement

#91 94-03-footer-ui
  src/client/components/footer/index.jsx
  src/client/components/footer/index.scss
  src/client/components/page/index.jsx
  src/client/components/rooms-summary-table/container.js
  src/client/logic/registration/actions.js
  src/client/pages/property-page/index.jsx
  src/client/regexValidationService.js
Labels: enhancement

#96 New header ui
  src/client/components/header/index.jsx
  src/client/components/header/index.scss
Labels: enhancement

#92 Added property pagination route
  src/api/routes/propertyRoutes.js
Labels: enhancement

#85 Server&database fixes
  .env
  server.js
  src/api/models/BedType.js
  src/api/models/City.js
  src/api/models/Country.js
  src/api/models/Facility.js
  src/api/models/FacilityCategory.js
  src/api/models/Message.js
  src/api/models/Property.js
  src/api/models/Reservation.js
  src/api/models/Review.js
  src/api/models/RoomType.js
  src/api/models/index.js
  src/api/orm.js
  src/api/testModels.js
Labels: enhancement

#98 create route for property with associations
  src/api/associations.js
  src/api/models/AccommodationRule.js
  src/api/repositories/propertyRepository.js
  src/api/services/property.js
  src/api/testModels.js
Labels: enhancement

#101 36 refactor registration
  src/client/logic/registration/actions.js
  src/client/logic/registration/saga.js
  src/client/logic/rootSaga.js
Labels: enhancement

#113 123 fix registration
  config/authPaths.js
  src/api/helpers/passport.js
  src/api/middleware/passport.middleware.js
  src/api/routes/userRoutes.js
  src/api/services/userToken.js
  src/client/components/registration/form.js
  src/client/components/user-cabinet/container.jsx
  src/client/components/user-cabinet/index.jsx
  src/client/helpers/api.js
  src/client/helpers/cookie-tool.js
  src/client/index.js
  src/client/logic/login/actions.js
  src/client/logic/login/saga.js
  src/client/logic/registration/saga.js
  src/client/regexValidationService.js
  src/client/services/authService.js
  src/client/services/userService.js
Labels: bug

#116 added get property details by id
  src/client/services/propertyService.js
Labels: enhancement

#137 139 search result item redesign 112 11 filter block ui
  src/client/components/header/index.jsx
  src/client/components/header/index.scss
  src/client/components/property-list-item/index.jsx
  src/client/components/property-list-item/index.scss
  src/client/components/quick-filter/index.jsx
  src/client/components/quick-filter/index.scss
  src/client/components/ranking-bar/49025597.ttf
  src/client/components/ranking-bar/83998502.ttf
  src/client/components/ranking-bar/index.jsx
  src/client/components/ranking-bar/index.scss
  src/client/components/search-summary/index.scss
  src/client/components/search/index.jsx
  src/client/components/search/index.scss
  src/client/logic/defaultState.js
  src/client/pages/search-page/index.jsx
  src/client/pages/search-page/index.scss
  src/client/styles/global.scss
Labels: enhancement

#148 Fix phone number, registration placeholder
  src/client/components/registration/form.js
  src/client/regexValidationService.js
Labels: bug, enhancement

#144 integrated header with login
  src/client/components/auth-hoc/index.jsx
  src/client/components/header/index.jsx
  src/client/logic/login/saga.js
  src/client/services/userService.js
Labels: enhancement

#155 added images to property creation
  src/api/repositories/propertyRepository.js
Labels: bug
